#include <stdio.h>
#include <string.h>
#include "checks.h"
#include "colors.h"
#include "version.h" // ← generated by CMake

void print_banner(void) {
    printf("%sSysDiag v%s — Diagnóstico del sistema%s\n", COLOR_CYAN, SYSDIAG_VERSION, COLOR_RESET);
    printf("--------------------------------------\n\n");
}

void print_version(void) {
    printf("SysDiag v%s\n", SYSDIAG_VERSION);
}

int main(int argc, char *argv[]) {
   
    if(argc > 1 && strcmp(argv[1], "--version") == 0) {
        print_version();
        return 0;
    }

    print_banner();
    run_all_checks();

    return 0;
}